### ISSUE TITLE
Error: encode_buffer_pcm_as_flac returned false.

### ISSUE THREAD

**Issue by son-nt123** [mmig/speech-to-flac#1]
It works fine on localhost but when i tried to run on server with HTTPS (because getUserMedia() no longer works on insecure origins), It throws an error:
Error: encode_buffer_pcm_as_flac returned false.
 Uncaught abort(0) at Error
    at jsStackTrace (https://mmig.github.io/speech-to-flac/libflac3-1.3.2.min.js:1:21182)
    at stackTrace (https://mmig.github.io/speech-to-flac/libflac3-1.3.2.min.js:1:21365)
    at abort (https://mmig.github.io/speech-to-flac/libflac3-1.3.2.min.js:14:8583)
    at Array.sg (https://mmig.github.io/speech-to-flac/libflac3-1.3.2.min.js:7:41450)
    at Hb (https://mmig.github.io/speech-to-flac/libflac3-1.3.2.min.js:5:12925)
    at wb (https://mmig.github.io/speech-to-flac/libflac3-1.3.2.min.js:5:1880)
    at $c (https://mmig.github.io/speech-to-flac/libflac3-1.3.2.min.js:5:100657)
    at Xc (https://mmig.github.io/speech-to-flac/libflac3-1.3.2.min.js:5:98850)
    at zd (https://mmig.github.io/speech-to-flac/libflac3-1.3.2.min.js:6:57725)
    at sd (https://mmig.github.io/speech-to-flac/libflac3-1.3.2.min.js:6:44703)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

Even when i run the demo at https://mmig.github.io/speech-to-flac/ , the same error is thrown. Can anyone help me?

**Comment by russaa** [comment]
sorry about that, https://mmig.github.io/speech-to-flac/ did contain an error which is [fixed now](https://github.com/mmig/speech-to-flac/commit/1c8e5ea0bd6db0ab6406aa00cc7a3e5907321886):

basically, the `.min.js` version initializes asynchronously, so before invoking any decoder/encoder related functions, there needs to be a check, if the library has initialized yet, e.g. something like this:
```javascript
if(!Flac.isReady()){
  Flac.onready = function(){
    doInitFlacEncoder();
  }
} else {
  doInitFlacEncoder();
}
```
_(this is not necessary for the non-minified versions of the library)_

... also note, that in the latest version 0.3.0 of the library the function  
`encode_buffer_pcm_as_flac`  
 is now called:  
`FLAC__stream_encoder_process_interleaved`  
_(see the [release note](https://github.com/mmig/libflac.js/releases/tag/v0.3.0) for breaking changes)_

**Comment by son-nt123** [comment]
Thank you so much for your prompt reply and the useful additional information too! That was exactly what happened and now i can send request to Google cloud speech. Thank you very much :D
